// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrate/introspection should go straight to Postgres, not through the
    // PgBouncer pooler (Neon's pooled endpoint doesn't support advisory locks).
    url: process.env["DIRECT_URL"],
  },
});
